# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-24 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0003_auto_20160824_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sleeperprofile',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='sleeperprofile',
            name='moreMetrics',
        ),
    ]
