# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-24 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0007_remove_sleepergroup_defunctmembers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sleep',
            name='active',
        ),
    ]
